"""The only code that touches a channel database. Every function takes a
connection and returns plain dicts; callers use this package's re-exports."""

from __future__ import annotations

from .blobs import (
    MAX_UPLOAD_BYTES,
    blob_append,
    blob_body,
    blob_get,
    blob_seal,
    body_digest,
    with_body_digest,
)
from .connection import connect, enable_wal, get_db_path, init_db, open_db, transaction
from .fields import (
    MESSAGE_FIELDS,
    MESSAGE_HEADERS,
    PIN_FIELDS,
    PIN_HEADERS,
    project,
    resolve_fields,
    row_to_dict,
)
from .messages import (
    delivery_read_at,
    fetch_events,
    fetch_inbox,
    fetch_message,
    fetch_thread,
    find_reply,
    insert_event,
    insert_message,
    is_addressed_to,
    list_messages,
    mark_delivered,
    mark_read,
    normalize_timestamp,
    observed_roles,
    require_party,
)
from .migrations import SCHEMA_VERSION
from .obligations import (
    confirm_resolution,
    delete_message,
    obligation_state,
    reopen_message,
    resolve_message,
    revise_message,
    set_work_status,
)
from .pins import (
    ack_tally,
    acks_by_message,
    approval_used,
    fetch_acknowledgements,
    fetch_awaiting_ack,
    open_rounds_for_pin,
    pin_ever_approved,
    pin_get,
    pin_history,
    pin_list,
    pin_set,
    round_voided_by,
    upsert_acknowledgement,
)
from .schema import (
    BROADCAST,
    FTS_OBJECTS,
    FTS_SCHEMA,
    FTS_VERSION,
    MIGRATIONS,
    SCHEMA,
    meta_get,
    meta_set,
    now,
)
from .search import QueryLimitError, search_messages
from .summary import ACTIONABLE_COUNTS, actionable_ids, channel_summary, last_movement, ready_work
from .supersede import (
    BACKFILL_EVENT,
    BACKFILL_FIELDS,
    BACKFILL_HEADERS,
    apply_supersede_backfill,
    cascade_preview,
    filter_candidates,
    pending_supersede_backfill,
    supersede_nudges,
    supersede_proposals_for_pin,
    undo_supersede_backfill,
)
from .views import board_feed, board_snapshot, board_thread

__all__ = [
    "ACTIONABLE_COUNTS",
    "BACKFILL_EVENT",
    "BACKFILL_FIELDS",
    "BACKFILL_HEADERS",
    "BROADCAST",
    "FTS_OBJECTS",
    "FTS_SCHEMA",
    "FTS_VERSION",
    "MAX_UPLOAD_BYTES",
    "MESSAGE_FIELDS",
    "MESSAGE_HEADERS",
    "MIGRATIONS",
    "PIN_FIELDS",
    "PIN_HEADERS",
    "SCHEMA",
    "SCHEMA_VERSION",
    "QueryLimitError",
    "ack_tally",
    "acks_by_message",
    "actionable_ids",
    "apply_supersede_backfill",
    "approval_used",
    "blob_append",
    "blob_body",
    "blob_get",
    "blob_seal",
    "board_feed",
    "board_snapshot",
    "board_thread",
    "body_digest",
    "cascade_preview",
    "channel_summary",
    "confirm_resolution",
    "connect",
    "delete_message",
    "delivery_read_at",
    "enable_wal",
    "fetch_acknowledgements",
    "fetch_awaiting_ack",
    "fetch_events",
    "fetch_inbox",
    "fetch_message",
    "fetch_thread",
    "filter_candidates",
    "find_reply",
    "get_db_path",
    "init_db",
    "insert_event",
    "insert_message",
    "is_addressed_to",
    "last_movement",
    "list_messages",
    "mark_delivered",
    "mark_read",
    "meta_get",
    "meta_set",
    "normalize_timestamp",
    "now",
    "obligation_state",
    "observed_roles",
    "open_db",
    "open_rounds_for_pin",
    "pending_supersede_backfill",
    "pin_ever_approved",
    "pin_get",
    "pin_history",
    "pin_list",
    "pin_set",
    "project",
    "ready_work",
    "reopen_message",
    "require_party",
    "resolve_fields",
    "resolve_message",
    "revise_message",
    "round_voided_by",
    "row_to_dict",
    "search_messages",
    "set_work_status",
    "supersede_nudges",
    "supersede_proposals_for_pin",
    "transaction",
    "undo_supersede_backfill",
    "upsert_acknowledgement",
    "with_body_digest",
]
